In [1]:
import numpy as np

### Matrices

In [2]:
matrix = np.arange(1, 13).reshape(3, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
matrix.shape

(3, 4)

In [7]:
matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [17]:
(matrix[0, :] + matrix[2, :]) / 2

array([ 5.,  6.,  7.,  8.])

### Right-multipy & left-multiply

In [5]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
x = np.array([1000, 100, 10, 1]).reshape((4, 1))

In [22]:
matrix @ x

array([[ 1234],
       [ 5678],
       [10122]])

In [23]:
y = np.array([0, 0.1, 1]).reshape((1, 3))

In [24]:
y @ matrix

array([[  9.5,  10.6,  11.7,  12.8]])

In [18]:
matrix @ np.array([1000, 100, 10, 1])

array([ 1234,  5678, 10122])

In [7]:
np.array([0, 0.1, 1]) @ matrix

array([ 9.5, 10.6, 11.7, 12.8])

### Singular value decomposition

In [45]:
u, s, vt = np.linalg.svd(matrix, full_matrices=False)
print('u:', u.shape, 'v:', vt.T.shape, 's:', s)

u: (3, 3) v: (4, 3) s: [  2.54368356e+01   1.72261225e+00   4.20733283e-16]


In [46]:
s

array([  2.54368356e+01,   1.72261225e+00,   4.20733283e-16])

In [47]:
u

array([[-0.20673589,  0.88915331,  0.40824829],
       [-0.51828874,  0.25438183, -0.81649658],
       [-0.82984158, -0.38038964,  0.40824829]])

In [49]:
u * s

array([[ -5.25870689e+00,   1.53166638e+00,   1.71763643e-16],
       [ -1.31836254e+01,   4.38201263e-01,  -3.43527287e-16],
       [ -2.11085440e+01,  -6.55263852e-01,   1.71763643e-16]])

In [59]:
u @ np.diag(s)

array([[ -5.25870689e+00,   1.53166638e+00,   1.71763643e-16],
       [ -1.31836254e+01,   4.38201263e-01,  -3.43527287e-16],
       [ -2.11085440e+01,  -6.55263852e-01,   1.71763643e-16]])

In [50]:
Us = (u * s)[:, :2]
Us

array([[ -5.25870689,   1.53166638],
       [-13.18362544,   0.43820126],
       [-21.10854399,  -0.65526385]])

In [51]:
Vt = vt[:2, :]
Vt

array([[-0.40361757, -0.46474413, -0.52587069, -0.58699725],
       [-0.73286619, -0.28984978,  0.15316664,  0.59618305]])

In [68]:
# The matrix can be approximated by s1 * u1 * v1t + s2 * u2 * v2t
# because the third singular value is quite small and hence discarded
print('Us:', Us.shape, 'Vt:', Vt.shape)
Us @ Vt  

Us: (3, 2) Vt: (2, 4)


array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [66]:
np.round(u @ u.T, 10)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [54]:
np.round(vt @ vt.T, 10)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [55]:
v = vt.T
matrix @ v

array([[ -5.25870689e+00,   1.53166638e+00,   1.11022302e-16],
       [ -1.31836254e+01,   4.38201263e-01,   1.33226763e-15],
       [ -2.11085440e+01,  -6.55263852e-01,   1.77635684e-15]])

In [56]:
u * s

array([[ -5.25870689e+00,   1.53166638e+00,   1.71763643e-16],
       [ -1.31836254e+01,   4.38201263e-01,  -3.43527287e-16],
       [ -2.11085440e+01,  -6.55263852e-01,   1.71763643e-16]])

In [57]:
np.diag(s)

array([[  2.54368356e+01,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.72261225e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   4.20733283e-16]])

In [58]:
u @ np.diag(s) @ vt

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [69]:
X = np.array([1, 1, 0, 1]).reshape((2, 2))

### My Own Example

In [70]:
X

array([[1, 1],
       [0, 1]])

In [71]:
u, s, vt = np.linalg.svd(X, full_matrices=False)
u, s, vt

(array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]),
 array([ 1.61803399,  0.61803399]),
 array([[ 0.52573111,  0.85065081],
        [-0.85065081,  0.52573111]]))

In [73]:
vt @ vt.T

array([[  1.00000000e+00,  -2.58515858e-17],
       [ -2.58515858e-17,   1.00000000e+00]])

In [74]:
v = vt.T

$$XV = U\Sigma$$

In [75]:
X @ v

array([[ 1.37638192, -0.3249197 ],
       [ 0.85065081,  0.52573111]])

In [76]:
u @ np.diag(s)

array([[ 1.37638192, -0.3249197 ],
       [ 0.85065081,  0.52573111]])

$$X = U\Sigma V^T $$

In [77]:
u @ np.diag(s) @ vt

array([[  1.00000000e+00,   1.00000000e+00],
       [  1.11022302e-16,   1.00000000e+00]])